# Introduction {#intro}

Social network theory is based on the study of social relations between actors so as to understand the formation of social structures by the analysis of basic local relations. Statistical models have started to play an increasingly important role because they give the possibility to explain the complexity of social behaviour and to investigate issues on how the global features of an observed network may be related to local network structures. The observed network is assumed to be generated by local social processes which depend on the self-organizing dyadic relations between actors. 

The crucial challenge for statistical models in social network theory is to capture and describe the dependency giving rise to network global topology allowing inference about whether certain local structures are more common than expected.

Exponential random graph models (ERGMs) [@hol:lei81] are an important family of models conceived to capture the complex dependence structure of an observed network allowing a reasonable interpretation of the underlying process which is supposed to have produced these structural properties. The dependence hypothesis at the basis of these models is that the connections between actors (edges) self-organize into small structures called configurations or network statistics. These are classical graph-theoretic structures such as degrees, cycles, etc. which can be directly incorporated in ERGMs as sufficient statistics with corresponding parameters measuring their importance in the observed network.

The computational intractability of ERGMs is the main barrier to estimation. Fortunately, recent theoretical developments and advanced computational procedures have given the possibility to make important progress to overcome statistical inference problems. 


