--- 
title: "Exponential random graph models with R"
subtitle: ""
author: "Alberto Caimo and Isabella Gollini"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
---

<style type="text/css">
.tabbed-pane { 
border-style: solid;
border-top-style: none;
border-width: 1px;
border-color: #e2e2e2; 
padding: 10px;
} 
.section h2 {
padding-top: 90px;
}
.section h3 {
padding-top: 70px;
}
</style>

# Preface {-}

Interest in statistical network analysis has grown massively in recent decades and its perspective and methods are now widely used in many scientific areas which involve the study of various types of networks for representing structure in many complex relational systems such as social relationships, information flows, protein interactions.

This manual is written for students in statistical network analysis courses as well as for people already engaged in these fields. Our aim is to offer the reader a balanced presentation of the fundamental statistical concepts and methods and practical advice on their effective implementation using R.

## About the authors {-}

### Alberto Caimo {-}

Alberto Caimo is a lecturer in Statistics in the School of Mathematical Sciences at the Dublin Institute of Technology, Ireland. His current research activity concerns the development and implementation of statistical modelling and computational approaches for complex relational data in a wide variety of applications involving interdisciplinary collaborations. Alberto is the author of the R package [`Bergm`](https://CRAN.R-project.org/package=Bergm) for the analysis of Bayesian exponential random graph models.

More info: [https://sites.google.com/site/albertocaimo](https://sites.google.com/site/albertocaimo/) 

### Isabella Gollini {-}

Isabella Gollini is a lecturer in Statistics in the Department of Economics, Mathematics and Statistics at the Birkbeck, University of London, UK. Her research activity focuses on cutting-edge statistical topics in the area of statistical modelling and computational statistics. Isabella is the leader of the teaching team of [Forwards: the R Foundation taskforce on women and under-represented groups](http://forwards.github.io/), and she is the author of several R packages, including [`lvm4net`](https://CRAN.R-project.org/package=lvm4net) for the analysis of latent variable models for network data using fast inferential procedures.

More info: [https://sites.google.com/site/isabellagollini](https://sites.google.com/site/isabellagollini/) 
